/*!
 * \file DrawServiceImpl.hpp
 * \author Enzo Ramos
 * \version 1.0
 *
 * \brief Define DrawService interface implementation.
 * 
 */

#ifndef DRAWSERVICEIMPL_HPP
#define DRAWSERVICEIMPL_HPP

#include "PetitPrince.hpp"

/*!
 * \class DrawServiceImpl DrawServiceImpl.hpp
 * \brief This class implements the DrawService interface generated by the idl
 * after compilation. The DrawService class inherited is the POA version. The
 * POA classes inherit the _impl_ classes which inherit the interfaces.
 * This class will define the implementation of each methods contained in the
 * interface (see cpp source file).
 */
class DrawServiceImpl : virtual public POA_PetitPrince::DrawService,
                        virtual public PortableServer::RefCountServantBase{
public:
    DrawServiceImpl();
    DrawServiceImpl(const DrawServiceImpl& orig);
    DrawServiceImpl(CORBA::ORB_var orb);
    virtual ~DrawServiceImpl();
    
    ::CORBA::Double area(::CORBA::Long id) override;
    ::CORBA::Double perimeter(::CORBA::Long id) override;
    void homothetie(::CORBA::Long id, ::CORBA::Double index) override;
    void translation(::CORBA::Long id, ::CORBA::Double x, ::CORBA::Double y) override;
    void rotation(::CORBA::Long id, ::CORBA::Double angle) override;
    void symCenter(::CORBA::Long id) override;
    void symAxial(::CORBA::Long id) override;
    
    void addDraw(::CORBA::Long pid, ::CORBA::Long cid) override;
    
    char* toString(::CORBA::Long id) override;
    
private:
    CORBA::ORB_var _orb;
    
};

#endif /* DRAWSERVICEIMPL_HPP */

