/*!
 * \file PetitPrinceServiceImpl.hpp
 * \author Jeremy Bidet
 * \version 1.0
 *
 * \brief Define PetitPrinceService interface implementation.
 * 
 */

#ifndef SERVICEDRAWIMPL_HPP
#define SERVICEDRAWIMPL_HPP

#include "PetitPrince.hpp"

#include <map>

using namespace std;

/*!
 * \class PetitPrinceServiceImpl PetitPrinceServiceImpl.hpp
 * \brief This class implements the PetitPrinceService interface generated by the idl
 * after compilation. The PetitPrinceService class inherited is the POA version. The
 * POA classes inherit the _impl_ classes which inherit the interfaces.
 * This class will define the implementation of each methods contained in the
 * interface (see cpp source file).
 */
class PetitPrinceServiceImpl:
        virtual public POA_PetitPrince::PetitPrinceService,
        virtual public PortableServer::RefCountServantBase {

public:
    PetitPrinceServiceImpl();
    PetitPrinceServiceImpl(const PetitPrinceServiceImpl& orig);
    PetitPrinceServiceImpl(CORBA::ORB_var orb);
    virtual ~PetitPrinceServiceImpl();
    
    /*!
     * \fn ::CORBA::Long createLine(const char* author, const ::PetitPrince::Point& a, const ::PetitPrince::Point& b)
     * \brief This method create a line with an author and two points as start and end coordinates
     * 
     * \param author the author of the draw
     * \param a a reference to the start point of the line
     * \param b a reference to the end point of the line
     * 
     * \throw InvalidDrawParams when creation fails
     * 
     * \return the id of the created draw
     * 
     */
    ::CORBA::Long createLine(const char* author, const ::PetitPrince::Point& a, const ::PetitPrince::Point& b) override;
    
    /*!
     * \fn ::CORBA::Long createCircle(const char* author, const ::PetitPrince::Point& center, ::CORBA::Double ray)
     * \brief This method create a circle with an author a center and a ray
     * 
     * \param author the author of the draw
     * \param center a reference to the center point of the circle
     * \param ray the ray of the circle
     * 
     * \throw InvalidDrawParams when creation fails
     * 
     * \return the id of the created draw
     * 
     */
    ::CORBA::Long createCircle(const char* author, const ::PetitPrince::Point& center, ::CORBA::Double ray) override;
    
    /*!
     * \fn ::CORBA::Long createEllipse(const char* author, const ::PetitPrince::Point& center, ::CORBA::Double long_ray, ::CORBA::Double short_ray)
     * \brief This method create a circle with an author a center and a ray
     * 
     * \param author the author of the draw
     * \param center a reference to the center point of the circle
     * \param ray the ray of the circle
     * 
     * \throw InvalidDrawParams when creation fails
     * 
     * \return the id of the created draw
     * 
     */
    ::CORBA::Long createEllipse(const char* author, const ::PetitPrince::Point& center, ::CORBA::Double long_ray, ::CORBA::Double short_ray) override;
    
    /*!
     * \fn ::CORBA::Long createPolygon(const char* author, const ::PetitPrince::PointSeq& pts)
     * \brief This method create a polygon with an author and a serie of points
     * 
     * \param author the author of the draw
     * \param pts a sequence of points
     * 
     * \throw InvalidDrawParams when creation fails
     * 
     * \return the id of the created draw
     * 
     */
    ::CORBA::Long createPolygon(const char* author, const ::PetitPrince::PointSeq& pts) override;
    
    /*!
     * \fn ::PetitPrince::LongSeq* getDraws(const char* author)
     * \brief This method return a sequence of id for the draws craeated by an author
     * 
     * \param author the author of the draws
     * 
     * \return the ids of the draws created by this author
     * 
     */
    ::PetitPrince::LongSeq* getDraws(const char* author) override;
    
    /*!
     * \fn void markDraw(::CORBA::Double mark, ::CORBA::Long id)
     * \brief This method give a mark for a draw
     * 
     * \param mark the given mark
     * \param id the id of the draw to apply the mark
     * 
     */
    void markDraw(::CORBA::Double mark, ::CORBA::Long id) override;
    

private:
    CORBA::ORB_var _orb;
    long cpt = 0;
    
public:
    static map<::CORBA::Long, ::PetitPrince::Draw*> _draw_list;
};


#endif /* SERVICEDRAWIMPL_HPP */

