/*
 *Auteur : E.Ramos, J.Bidet, J.Ramsamy
 *Description : Ce module definie la structure des "dessins" ainsi que le designe du service
 */

module PetitPrince {

    struct Point {
        double x;
        double y;
    };

    valuetype Draw;

    typedef sequence<Draw> DrawSeq;
    typedef sequence<Point> PointSeq;

    valuetype Draw {

        readonly attribute long id;
        readonly attribute string author;
        attribute DrawSeq inner_draws;
        attribute double mark;

        double area();
        double perimeter();
        void homothetie(in double indice);
        void translation(in double x, in double y);
        void rotation(in double angle);
        void symCenter();
        void symAxial();

        string toString();
    };

    valuetype Line : Draw {
        attribute Point start;
        attribute Point end;
    };

    valuetype Circle : Draw {
        attribute Point center;
        attribute double ray;
    };
    
    valuetype Ellipse : Draw {
        attribute Point center;
        attribute double long_ray;
        attribute double short_ray;
    };

    valuetype Polygon : Draw {
        attribute PointSeq points_list;
    };

    interface DrawService {
        exception non_applicable{string msg;};
        exception unexpected_draw{string msg;};

        double area(in Draw d)
            raises(non_applicable);
        double perimeter(in Draw d)
            raises(non_applicable);
        void homothetie(in Draw d, in double indice);
        void translation(in Draw d, in double x, in double y);
        void rotation(in Draw d, in double angle);
        void symCenter(in Draw d);
        void symAxial(in Draw d);
        void addDraw(in Draw parent, in Draw child)
            raises(unexpected_draw);

        string toString(in Draw d);
    };

    interface PetitPrinceService {
        attribute DrawSeq draw_list;

        void pushDraw(in Draw d);
        Draw getDraw(in long id);
        void markDraw(in double mark, in long id);
    };

};